version: "3"
services:
  php-workspace:
    image: php:7.4-fpm
    build: ./php
    volumes:
      - ./code:/var/www/html/

  nginx:
    image: nginx:latest
    build: ./nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./code:/usr/share/nginx/html/

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root